//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iDAutomatedTests.FrontEnd.Apps.OldLayoutManager.Locators {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class OldLayoutManagerElements {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OldLayoutManagerElements() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("iDAutomatedTests.FrontEnd.Apps.OldLayoutManager.Locators.OldLayoutManagerElements" +
                            "", typeof(OldLayoutManagerElements).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&quot;wikiPageControl_wikiHeaderControl_pnDraft&quot;]/a.
        /// </summary>
        internal static string EditLayoutDraft {
            get {
                return ResourceManager.GetString("EditLayoutDraft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&quot;wikiPageControl_wikiHeaderControl_pnLive&quot;]/a.
        /// </summary>
        internal static string EditLayoutLive {
            get {
                return ResourceManager.GetString("EditLayoutLive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&quot;editSelectorOff&quot;].
        /// </summary>
        internal static string EditLayoutOption {
            get {
                return ResourceManager.GetString("EditLayoutOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&quot;wikiPageControl_wikiHeaderControl_pnPreview&quot;]/a.
        /// </summary>
        internal static string EditLayoutStaging {
            get {
                return ResourceManager.GetString("EditLayoutStaging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&quot;panelHelp&quot;]/div.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&quot;ui-id-1&quot;].
        /// </summary>
        internal static string LayoutsTab {
            get {
                return ResourceManager.GetString("LayoutsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@id=&apos;buttonLayoutManage&apos;]/span[.=&apos;Manage Layout&apos;].
        /// </summary>
        internal static string ManageLayout {
            get {
                return ResourceManager.GetString("ManageLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&quot;buttonLayoutAdd&quot;]/span.
        /// </summary>
        internal static string NewLayout {
            get {
                return ResourceManager.GetString("NewLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@class=&apos;ui-dialog-buttonpane ui-widget-content ui-helper-clearfix&apos;]//input[@class=&apos;systemButtonFixed&apos; and @value=&apos;&lt; Back&apos;].
        /// </summary>
        internal static string NewLayoutBackButton {
            get {
                return ResourceManager.GetString("NewLayoutBackButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@class=&apos;ui-dialog-buttonpane ui-widget-content ui-helper-clearfix&apos;]//input[@class=&apos;systemButtonFixed&apos; and @value=&apos;Cancel&apos;].
        /// </summary>
        internal static string NewLayoutCancelButton {
            get {
                return ResourceManager.GetString("NewLayoutCancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&quot;PAddPage_modalWizard_DescriptionTextBox&quot;].
        /// </summary>
        internal static string NewLayoutDescriptionTextArea {
            get {
                return ResourceManager.GetString("NewLayoutDescriptionTextArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@class=&apos;ui-dialog-buttonpane ui-widget-content ui-helper-clearfix&apos;]//input[@class=&apos;systemButtonFixed&apos; and @value=&apos;Finish&apos;].
        /// </summary>
        internal static string NewLayoutFinishButton {
            get {
                return ResourceManager.GetString("NewLayoutFinishButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@class=&apos;ui-dialog-buttonpane ui-widget-content ui-helper-clearfix&apos;]//input[@class=&apos;systemButtonFixed&apos; and @value=&apos;Next &gt;&apos;].
        /// </summary>
        internal static string NewLayoutNextButton {
            get {
                return ResourceManager.GetString("NewLayoutNextButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&quot;PAddPage_modalWizard_ActorSelector_buttonAddActor&quot;].
        /// </summary>
        internal static string NewLayoutOwnerTabAddUsersButton {
            get {
                return ResourceManager.GetString("NewLayoutOwnerTabAddUsersButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&quot;PAddPage_modalWizard_ActorSelector_actorSelectorDropDownSearchLocation&quot;].
        /// </summary>
        internal static string NewLayoutOwnerTabFindUserAddFromDropDownList {
            get {
                return ResourceManager.GetString("NewLayoutOwnerTabFindUserAddFromDropDownList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&quot;PAddPage_modalWizard_ActorSelector_buttonCancel&quot;].
        /// </summary>
        internal static string NewLayoutOwnerTabFindUserCancelButton {
            get {
                return ResourceManager.GetString("NewLayoutOwnerTabFindUserCancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&quot;textEmail&quot;].
        /// </summary>
        internal static string NewLayoutOwnerTabFindUserEmailTextBox {
            get {
                return ResourceManager.GetString("NewLayoutOwnerTabFindUserEmailTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&quot;textGivenName&quot;].
        /// </summary>
        internal static string NewLayoutOwnerTabFindUserGivenNameTextBox {
            get {
                return ResourceManager.GetString("NewLayoutOwnerTabFindUserGivenNameTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&quot;checkActor_1&quot;].
        /// </summary>
        internal static string NewLayoutOwnerTabFindUserGuestCheckBox {
            get {
                return ResourceManager.GetString("NewLayoutOwnerTabFindUserGuestCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&quot;textLastName&quot;].
        /// </summary>
        internal static string NewLayoutOwnerTabFindUserLastNameTextBox {
            get {
                return ResourceManager.GetString("NewLayoutOwnerTabFindUserLastNameTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&quot;PAddPage_modalWizard_ActorSelector_buttonOK&quot;].
        /// </summary>
        internal static string NewLayoutOwnerTabFindUserOkButton {
            get {
                return ResourceManager.GetString("NewLayoutOwnerTabFindUserOkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&quot;buttonSearchActor&quot;].
        /// </summary>
        internal static string NewLayoutOwnerTabFindUserSearchButton {
            get {
                return ResourceManager.GetString("NewLayoutOwnerTabFindUserSearchButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&quot;PAddPage_modalWizard_PublishFutureDate&quot;].
        /// </summary>
        internal static string NewLayoutPublishFutureDateRadioOption {
            get {
                return ResourceManager.GetString("NewLayoutPublishFutureDateRadioOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&quot;PAddPage_modalWizard_PublishImmediately&quot;].
        /// </summary>
        internal static string NewLayoutPublishImmediatelyRadioOption {
            get {
                return ResourceManager.GetString("NewLayoutPublishImmediatelyRadioOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&quot;wikiPageControl_wikiHeaderControl_pnSaveLive&quot;]/table/tbody/tr/td[2].
        /// </summary>
        internal static string NewLayoutPublishLiveOption {
            get {
                return ResourceManager.GetString("NewLayoutPublishLiveOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&quot;saveDropDownMenu&quot;]/div[3]/table/tbody/tr/td[2]/a.
        /// </summary>
        internal static string NewLayoutPublishStagingOption {
            get {
                return ResourceManager.GetString("NewLayoutPublishStagingOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&quot;saveDropDownMenu&quot;]/div[1]/table/tbody/tr/td[2]/a.
        /// </summary>
        internal static string NewLayoutSaveDraftContinueEditingOption {
            get {
                return ResourceManager.GetString("NewLayoutSaveDraftContinueEditingOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&quot;saveDropDownMenu&quot;]/div[2]/table/tbody/tr/td[2]/a.
        /// </summary>
        internal static string NewLayoutSaveDraftExitOption {
            get {
                return ResourceManager.GetString("NewLayoutSaveDraftExitOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&quot;saveOff&quot;].
        /// </summary>
        internal static string NewLayoutSaveOption {
            get {
                return ResourceManager.GetString("NewLayoutSaveOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&quot;ApplyLayout&quot;].
        /// </summary>
        internal static string NewLayoutSavePopupApplyCheckBox {
            get {
                return ResourceManager.GetString("NewLayoutSavePopupApplyCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@class=&apos;ui-dialog-buttonset&apos;]//button[@class=&apos;ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only&apos;]/span[.=&apos;Cancel&apos;].
        /// </summary>
        internal static string NewLayoutSavePopupCancelButton {
            get {
                return ResourceManager.GetString("NewLayoutSavePopupCancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //table[@class=&apos;modalTable&apos;]/tbody//tr/td//textarea[@id=&apos;svMessage&apos;].
        /// </summary>
        internal static string NewLayoutSavePopupDescriptionTextArea {
            get {
                return ResourceManager.GetString("NewLayoutSavePopupDescriptionTextArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@class=&apos;ui-dialog-buttonset&apos;]//button[@class=&apos;ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only&apos;]/span[.=&apos;Save&apos;].
        /// </summary>
        internal static string NewLayoutSavePopupSaveButton {
            get {
                return ResourceManager.GetString("NewLayoutSavePopupSaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&quot;PAddPage_modalWizard_PageExpiryDate_ExCheckBox&quot;].
        /// </summary>
        internal static string NewLayoutSetExpiryDateCheckBox {
            get {
                return ResourceManager.GetString("NewLayoutSetExpiryDateCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&quot;PAddPage_modalWizard_NameTextBox&quot;].
        /// </summary>
        internal static string NewLayoutTitleTextBox {
            get {
                return ResourceManager.GetString("NewLayoutTitleTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&quot;PAddPage_modalWizard_URLPartControl_URLPartTextBox&quot;].
        /// </summary>
        internal static string NewLayoutURLTextBox {
            get {
                return ResourceManager.GetString("NewLayoutURLTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&quot;buttonSubsiteTemplateAdd&quot;]/span.
        /// </summary>
        internal static string NewSubsiteTemplate {
            get {
                return ResourceManager.GetString("NewSubsiteTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&quot;panelProperties&quot;]/div.
        /// </summary>
        internal static string Properties {
            get {
                return ResourceManager.GetString("Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&quot;quickSave&quot;].
        /// </summary>
        internal static string QuickSave {
            get {
                return ResourceManager.GetString("QuickSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&quot;ui-id-2&quot;].
        /// </summary>
        internal static string SubsiteTemplatesTab {
            get {
                return ResourceManager.GetString("SubsiteTemplatesTab", resourceCulture);
            }
        }
    }
}
