//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Generic.Locators.Admin {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class iDWelcomePageElements {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal iDWelcomePageElements() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Core.Generic.Locators.Admin.iDWelcomePageElements", typeof(iDWelcomePageElements).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@class=&apos;adminBreadcrumb&apos;]/a[@class=&apos;adminTitleLinkAbout&apos;].
        /// </summary>
        internal static string AboutLink {
            get {
                return ResourceManager.GetString("AboutLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //tbody/tr//td[contains(@id,&apos;menuNodes&apos;)]/span/a[.=&apos;{0}&apos;].
        /// </summary>
        internal static string AdminApplicationLocator {
            get {
                return ResourceManager.GetString("AdminApplicationLocator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //img[contains(@src,&apos;icon_utils.gif&apos;)]//..//../span[contains(text(),&apos;Administration&apos;)].
        /// </summary>
        internal static string AdministrationExpand {
            get {
                return ResourceManager.GetString("AdministrationExpand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //tbody/tr//td/span[.=&apos;{0}&apos;]/../..//td/span[.=&apos;{1}&apos;].
        /// </summary>
        internal static string ApplicationExpand {
            get {
                return ResourceManager.GetString("ApplicationExpand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //a[contains(text(),&apos;Subsite Admin&apos;)].
        /// </summary>
        internal static string FirstTreeElementInExpandedSubsite {
            get {
                return ResourceManager.GetString("FirstTreeElementInExpandedSubsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@class=&apos;adminBreadcrumb&apos;]/a[@class=&apos;adminTitleLinkHelp&apos;].
        /// </summary>
        internal static string HelpLink {
            get {
                return ResourceManager.GetString("HelpLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&quot;tree1&quot;]/div/div/table[2]/tbody/tr/td[2]/div[1]/table[2]/tbody/tr/td[2]/div[1]/table[1]/tbody/tr/td[1]/img.
        /// </summary>
        internal static string HomeExpand {
            get {
                return ResourceManager.GetString("HomeExpand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@id=&apos;userDisplay&apos;]/a[.=&apos;Logout&apos;].
        /// </summary>
        internal static string LogoutLink {
            get {
                return ResourceManager.GetString("LogoutLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@id=&apos;tabBox&apos;]//div[@id=&apos;AdminWelcomePage&apos;]/ul[@id=&apos;AdminWelcomePageList&apos;]//li/a[.=&apos;Task List&apos;].
        /// </summary>
        internal static string TaskListTab {
            get {
                return ResourceManager.GetString("TaskListTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@id=&apos;tabBox&apos;]//div[@id=&apos;AdminWelcomePage&apos;]/ul[@id=&apos;AdminWelcomePageList&apos;]//li/a[.=&apos;User Details&apos;].
        /// </summary>
        internal static string UserDetailsTab {
            get {
                return ResourceManager.GetString("UserDetailsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //img[contains(@src,&apos;icon_utils.gif&apos;)]//following-sibling::a[contains(text(),&apos;Utilities&apos;)].
        /// </summary>
        internal static string UtilitiesExapand {
            get {
                return ResourceManager.GetString("UtilitiesExapand", resourceCulture);
            }
        }
    }
}
