//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Generic.Locators.Admin {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class OwnerSelectControl {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OwnerSelectControl() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Core.Generic.Locators.Admin.OwnerSelectControl", typeof(OwnerSelectControl).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //select[@id=&apos;Owners_actorSelectorDropDownSearchLocation&apos;].
        /// </summary>
        internal static string AddFromDropDownInUserSearch {
            get {
                return ResourceManager.GetString("AddFromDropDownInUserSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[contains(@class,&apos;addRemoveButtons&apos;)]//input[@id=&apos;Owners_buttonAddActor&apos;].
        /// </summary>
        internal static string AddOwnersButton {
            get {
                return ResourceManager.GetString("AddOwnersButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //input[@id=&apos;Owners_buttonCancel&apos;].
        /// </summary>
        internal static string ClickCancelToEndSearchResults {
            get {
                return ResourceManager.GetString("ClickCancelToEndSearchResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //input[@id=&apos;Owners_buttonOK&apos;].
        /// </summary>
        internal static string ClickOkToAddUserFromSearchResults {
            get {
                return ResourceManager.GetString("ClickOkToAddUserFromSearchResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //input[@id=&apos;Owners_textEmail&apos;].
        /// </summary>
        internal static string EmailInOwnerUserSearch {
            get {
                return ResourceManager.GetString("EmailInOwnerUserSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //input[@id=&apos;Owners_textGivenName&apos;].
        /// </summary>
        internal static string GivenNameOwnerUserSearch {
            get {
                return ResourceManager.GetString("GivenNameOwnerUserSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //input[@id=&apos;Owners_textLastName&apos;].
        /// </summary>
        internal static string lastNameOwnerUserSearch {
            get {
                return ResourceManager.GetString("lastNameOwnerUserSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //input[@id=&apos;buttonSearchActor&apos;].
        /// </summary>
        internal static string SearchButtonInUserSearch {
            get {
                return ResourceManager.GetString("SearchButtonInUserSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //table[@id=&apos;Owners_tableActorResults&apos;]//tr[contains(@actorname,&apos;{0}&apos;)]/td[@class=&apos;userSelectorCheckbox&apos;]/input[@type=&apos;checkbox&apos;].
        /// </summary>
        internal static string SelectParticularUserCheckBoxSearchResults {
            get {
                return ResourceManager.GetString("SelectParticularUserCheckBoxSearchResults", resourceCulture);
            }
        }
    }
}
