//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Generic.Locators.Admin {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WorkflowControlElements {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WorkflowControlElements() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Core.Generic.Locators.Admin.WorkflowControlElements", typeof(WorkflowControlElements).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //input[@type=&apos;submit&apos; and @id=&apos;createNewWorkflow&apos;].
        /// </summary>
        internal static string AddWorkFlow_CreateWorkflowButton {
            get {
                return ResourceManager.GetString("AddWorkFlow_CreateWorkflowButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //textarea[@id=&apos;newWorkflowDesc&apos;].
        /// </summary>
        internal static string AddWorkFlow_Description {
            get {
                return ResourceManager.GetString("AddWorkFlow_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //input[@id=&apos;newWorkflowName&apos;].
        /// </summary>
        internal static string AddWorkflow_Title {
            get {
                return ResourceManager.GetString("AddWorkflow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //a[contains(@href,&apos;javascript:window.open&apos;) and contains(text(),&apos;Add Workflow&apos;)].
        /// </summary>
        internal static string AddWorkflowMenuItem {
            get {
                return ResourceManager.GetString("AddWorkflowMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //img[contains(@src,&apos;icon_app_workflow.gif&apos;)]//following-sibling::a[contains(text(),&apos;Workflow&apos;)].
        /// </summary>
        internal static string WorkflowMenuUnderUtilities {
            get {
                return ResourceManager.GetString("WorkflowMenuUnderUtilities", resourceCulture);
            }
        }
    }
}
