//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iDAutomatedTests.Admin.Apps.News.Locators {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class NewsPageElements {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NewsPageElements() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("iDAutomatedTests.Admin.Apps.News.Locators.NewsPageElements", typeof(NewsPageElements).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //input[@id=&apos;ArticleApproved&apos;].
        /// </summary>
        internal static string ApproveCheckBox {
            get {
                return ResourceManager.GetString("ApproveCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //input[@id=&apos;NewsButtons_Back&apos;].
        /// </summary>
        internal static string BackButton {
            get {
                return ResourceManager.GetString("BackButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //input[@id=&apos;NewsButtons_Cancel&apos;].
        /// </summary>
        internal static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //input[@id=&apos;ArticleExpiryDate_ExCheckBox&apos;].
        /// </summary>
        internal static string ExpiryDateCheckBox {
            get {
                return ResourceManager.GetString("ExpiryDateCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //tbody/tr//td/span/a[.=&apos;Add News&apos;].
        /// </summary>
        internal static string MainMenuAddNewsLink {
            get {
                return ResourceManager.GetString("MainMenuAddNewsLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //body.
        /// </summary>
        internal static string NewsArticleBody {
            get {
                return ResourceManager.GetString("NewsArticleBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ArticleBody_editor_contentIframe.
        /// </summary>
        internal static string NewsArticleBodyFrameID {
            get {
                return ResourceManager.GetString("NewsArticleBodyFrameID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //input[@id=&apos;NewsButtons_Finish&apos;].
        /// </summary>
        internal static string NewsFinishButton {
            get {
                return ResourceManager.GetString("NewsFinishButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //textarea[@id=&apos;Summary&apos;].
        /// </summary>
        internal static string NewsSummaryTextArea {
            get {
                return ResourceManager.GetString("NewsSummaryTextArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //input[@id=&apos;ArticleTitle&apos;].
        /// </summary>
        internal static string NewsTitleTextBox {
            get {
                return ResourceManager.GetString("NewsTitleTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //input[@id=&apos;HasTitleAlternateLink&apos;].
        /// </summary>
        internal static string NewsTitleURLLinkCheckBox {
            get {
                return ResourceManager.GetString("NewsTitleURLLinkCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //input[@id=&apos;TitleAlternateLink&apos;].
        /// </summary>
        internal static string NewsTitleURLLinkTextBox {
            get {
                return ResourceManager.GetString("NewsTitleURLLinkTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //input[@id=&apos;NewsButtons_Next&apos;].
        /// </summary>
        internal static string NextButton {
            get {
                return ResourceManager.GetString("NextButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //input[@id=&apos;OpenNewWindowTitleAlternateLink&apos;].
        /// </summary>
        internal static string OpenInNewWindowCheckBox {
            get {
                return ResourceManager.GetString("OpenInNewWindowCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //select[@id=&apos;PriorityLevel&apos;].
        /// </summary>
        internal static string PriorityDropDownList {
            get {
                return ResourceManager.GetString("PriorityDropDownList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //input[@id=&apos;HasPublishDate&apos;].
        /// </summary>
        internal static string PublishDateCheckBox {
            get {
                return ResourceManager.GetString("PublishDateCheckBox", resourceCulture);
            }
        }
    }
}
