//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iDAutomatedTests.Admin.Apps.OnlineForms.Locators {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class OnlineFormsElements {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OnlineFormsElements() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("iDAutomatedTests.Admin.Apps.OnlineForms.Locators.OnlineFormsElements", typeof(OnlineFormsElements).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@id=&apos;FolderOptionsPage&apos;]//input[@id=&apos;AddFolder&apos;].
        /// </summary>
        internal static string AddFolderButtonInOnlineFormList_Options {
            get {
                return ResourceManager.GetString("AddFolderButtonInOnlineFormList_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //a[contains(@class,&apos;deletefolder&apos;)].
        /// </summary>
        internal static string DeleteFolderButtonInHeader {
            get {
                return ResourceManager.GetString("DeleteFolderButtonInHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@id=&apos;FolderOptionsPage&apos;]//input[@id=&apos;DeleteFolder&apos;].
        /// </summary>
        internal static string DeleteFolderButtonInOnlineFormList {
            get {
                return ResourceManager.GetString("DeleteFolderButtonInOnlineFormList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@class=&apos;wz_buttons buttonFooter&apos;]//input[@id=&apos;CancelButton&apos;].
        /// </summary>
        internal static string DeleteFolderConfirmationCancelButton {
            get {
                return ResourceManager.GetString("DeleteFolderConfirmationCancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@class=&apos;wz_buttons buttonFooter&apos;]//input[@id=&apos;OKButton&apos;].
        /// </summary>
        internal static string DeleteFolderConfirmationOkButton {
            get {
                return ResourceManager.GetString("DeleteFolderConfirmationOkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //input[@id=&apos;FolderDelete&apos;].
        /// </summary>
        internal static string DeletFolderConfirmationCheckBox {
            get {
                return ResourceManager.GetString("DeletFolderConfirmationCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //a[contains(@class,&apos;editfolder&apos;)].
        /// </summary>
        internal static string EditFolderButtonInHeader {
            get {
                return ResourceManager.GetString("EditFolderButtonInHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@id=&apos;FolderOptionsPage&apos;]//input[@id=&apos;EditFolder&apos;].
        /// </summary>
        internal static string EditFolderButtonInOnlineFormList {
            get {
                return ResourceManager.GetString("EditFolderButtonInOnlineFormList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //input[@id=&apos;FolderActive&apos;].
        /// </summary>
        internal static string FolderActiveCheckbox {
            get {
                return ResourceManager.GetString("FolderActiveCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //textarea[@id=&apos;FolderDescription&apos;].
        /// </summary>
        internal static string FolderDescriptioninAddFolderWizard {
            get {
                return ResourceManager.GetString("FolderDescriptioninAddFolderWizard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //form[@id=&apos;form1&apos;]//div[@id=&apos;folderView&apos;]//span//div//tbody//span[contains(text(),&apos;{0}&apos;)]//..//img[contains(@src,&apos;icon_folderclosedsecure.gif&apos;)].
        /// </summary>
        internal static string FolderListConfirmFolderIsActive {
            get {
                return ResourceManager.GetString("FolderListConfirmFolderIsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //form[@id=&apos;form1&apos;]//div[@id=&apos;folderView&apos;]//span//div//tbody//span[contains(text(),&apos;{0}&apos;)]//..//img[contains(@src,&apos;icon_folderinactivesecure.gif&apos;)].
        /// </summary>
        internal static string FolderListConfirmFolderIsInActive {
            get {
                return ResourceManager.GetString("FolderListConfirmFolderIsInActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@id=&apos;wizardBox&apos;]//input[@id=&apos;FolderName&apos;].
        /// </summary>
        internal static string FolderTitleAddFolderWizard {
            get {
                return ResourceManager.GetString("FolderTitleAddFolderWizard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //input[@id=&apos;AddFolderButtons_Back&apos;].
        /// </summary>
        internal static string FolderWizardBackButton {
            get {
                return ResourceManager.GetString("FolderWizardBackButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //input[@id=&apos;AddFolderButtons_Cancel&apos;].
        /// </summary>
        internal static string FolderWizardCancelButton {
            get {
                return ResourceManager.GetString("FolderWizardCancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //input[@id=&apos;AddFolderButtons_Finish&apos;].
        /// </summary>
        internal static string FolderWizardFinishButton {
            get {
                return ResourceManager.GetString("FolderWizardFinishButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //img[@id=&apos;FolderActiveConfirmation&apos; and contains(@src,&apos;true.gif&apos;)].
        /// </summary>
        internal static string FolderWizardFinishStepConfirmFolderIsActive {
            get {
                return ResourceManager.GetString("FolderWizardFinishStepConfirmFolderIsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //img[@id=&apos;FolderActiveConfirmation&apos; and contains(@src,&apos;false.gif&apos;)].
        /// </summary>
        internal static string FolderWizardFinishStepConfirmFolderIsInActive {
            get {
                return ResourceManager.GetString("FolderWizardFinishStepConfirmFolderIsInActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //input[@id=&apos;AddFolderButtons_Next&apos;].
        /// </summary>
        internal static string FolderWizardNextButton {
            get {
                return ResourceManager.GetString("FolderWizardNextButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@id=&apos;selectAllFuture&apos;]//div[@class=&apos;checkBoxSurround&apos;].
        /// </summary>
        internal static string FolderWizardWorkflowTabGetAccessForAllFutureWorkflowToThisFolderCheckBox {
            get {
                return ResourceManager.GetString("FolderWizardWorkflowTabGetAccessForAllFutureWorkflowToThisFolderCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //tbody//tr//td//div[@class=&apos;itemTitle&apos; and contains(text(),&apos;{0}&apos;)]//..//..//td//input[@value=&apos;isDefault&apos;].
        /// </summary>
        internal static string FolderWizardWorkflowTabMakeAnyParticularWorkflowAsDefaultRadioButton {
            get {
                return ResourceManager.GetString("FolderWizardWorkflowTabMakeAnyParticularWorkflowAsDefaultRadioButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //tbody//tr//td//div[@class=&apos;itemTitle&apos; and contains(text(),&apos;{0}&apos;)]//..//..//td//input[contains(@id,&apos;WorkflowControl_workFlowSelect&apos;)].
        /// </summary>
        internal static string FolderWizardWorkflowTabSelectAnyParticularWorkflowCheckBox {
            get {
                return ResourceManager.GetString("FolderWizardWorkflowTabSelectAnyParticularWorkflowCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //input[@id=&apos;WorkflowControl_workFlowSelect_workflowDataGrid_checkAll&apos;].
        /// </summary>
        internal static string FolderWizardWorkflowTabTitleDescriptionSelectAllWorkflowCheckBox {
            get {
                return ResourceManager.GetString("FolderWizardWorkflowTabTitleDescriptionSelectAllWorkflowCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //a[@target=&apos;main&apos; and contains(text(),&apos;Manage Forms&apos;)].
        /// </summary>
        internal static string ManageForms {
            get {
                return ResourceManager.GetString("ManageForms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //a[contains(@class,&apos;movefolder&apos;)].
        /// </summary>
        internal static string MoveFolderButtonInHeader {
            get {
                return ResourceManager.GetString("MoveFolderButtonInHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //a[contains(@class,&apos;newfolder&apos;)].
        /// </summary>
        internal static string NewFolderButtonInHeader {
            get {
                return ResourceManager.GetString("NewFolderButtonInHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //a[contains(@class,&apos;recyclebin&apos;)].
        /// </summary>
        internal static string RecycleBinInHeader {
            get {
                return ResourceManager.GetString("RecycleBinInHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //form[@id=&apos;form1&apos;]//div[@id=&apos;folderView&apos;]//span//div//tbody//span[contains(text(),&apos;{0}&apos;)].
        /// </summary>
        internal static string SelectFolderToManageForms {
            get {
                return ResourceManager.GetString("SelectFolderToManageForms", resourceCulture);
            }
        }
    }
}
