//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iDAutomatedUITests.UIElements {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CleverToolsPageElements {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CleverToolsPageElements() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("iDAutomatedUITests.UIElements.CleverToolsPageElements", typeof(CleverToolsPageElements).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //select[@id=&apos;AppList&apos;].
        /// </summary>
        internal static string AddToolApplicationDropDownList {
            get {
                return ResourceManager.GetString("AddToolApplicationDropDownList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //input[@class=&apos;button button-ungroupApply  button-infooter-apply&apos;].
        /// </summary>
        internal static string AddToolApplyButton {
            get {
                return ResourceManager.GetString("AddToolApplyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //input[@id=&apos;AddApplicationButtons_Cancel&apos;].
        /// </summary>
        internal static string AddToolCancelButton {
            get {
                return ResourceManager.GetString("AddToolCancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //table[@id=&apos;AppLocation&apos;]/tbody/tr//td/input[@id=&apos;AppLocation_1&apos;].
        /// </summary>
        internal static string AddToolLocationDropDownItem {
            get {
                return ResourceManager.GetString("AddToolLocationDropDownItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //table[@id=&apos;AppLocation&apos;]/tbody/tr//td/input[@id=&apos;AppLocation_0&apos;].
        /// </summary>
        internal static string AddToolLocationListItem {
            get {
                return ResourceManager.GetString("AddToolLocationListItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //input[@id=&apos;AddApplicationButtons_Ok&apos;].
        /// </summary>
        internal static string AddToolOKButton {
            get {
                return ResourceManager.GetString("AddToolOKButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //tbody/tr//td[contains(@id,&apos;menuNodess&apos;)]/span/a[.=&apos;Add Tool&apos;].
        /// </summary>
        internal static string AddToolSubMenuOption {
            get {
                return ResourceManager.GetString("AddToolSubMenuOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //input[@id=&apos;CustomEditButtons_Apply&apos;].
        /// </summary>
        internal static string EditIconsApplyButton {
            get {
                return ResourceManager.GetString("EditIconsApplyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //input[@id=&apos;CustomEditButtons_Cancel&apos;].
        /// </summary>
        internal static string EditIconsCancelButton {
            get {
                return ResourceManager.GetString("EditIconsCancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //input[@id=&apos;CustomEditButtons_Ok&apos;].
        /// </summary>
        internal static string EditIconsOKButton {
            get {
                return ResourceManager.GetString("EditIconsOKButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //input[@id=&quot;ShowIconsOnFront&quot;].
        /// </summary>
        internal static string EditIconsShowIconsOnFrontEnd {
            get {
                return ResourceManager.GetString("EditIconsShowIconsOnFrontEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //tbody/tr//td[contains(@id,&apos;menuNodess&apos;)]/span/a[.=&apos;Edit Icons&apos;].
        /// </summary>
        internal static string EditIconsSubMenuOption {
            get {
                return ResourceManager.GetString("EditIconsSubMenuOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //li[@class=&apos;ui-state-default ui-corner-top&apos;]/a[.=&apos;Drop Down Items&apos;].
        /// </summary>
        internal static string EditToolDropDownItemsTab {
            get {
                return ResourceManager.GetString("EditToolDropDownItemsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //li[@class=&apos;ui-state-default ui-corner-top ui-tabs-active ui-state-active&apos;]/a[.=&apos;List Items&apos;].
        /// </summary>
        internal static string EditToolListItemsTab {
            get {
                return ResourceManager.GetString("EditToolListItemsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //table[@id=&apos;ToolsDropDownList&apos;]//tbody//tr//td[text()=&apos;{0}&apos;]/..//td//input[contains(@id,&apos;MoveDown&apos;)].
        /// </summary>
        internal static string EditToolMoveDownButtonInDropDownItems {
            get {
                return ResourceManager.GetString("EditToolMoveDownButtonInDropDownItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //table[@id=&apos;ToolsList&apos;]//tbody//tr//td[text()=&apos;{0}&apos;]/..//td//input[contains(@id,&apos;MoveDown&apos;)].
        /// </summary>
        internal static string EditToolMoveDownButtonInListItems {
            get {
                return ResourceManager.GetString("EditToolMoveDownButtonInListItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //table[@id=&apos;ToolsDropDownList&apos;]//tbody//tr//td[text()=&apos;{0}&apos;]/..//td//input[contains(@id,&apos;MoveUp&apos;)].
        /// </summary>
        internal static string EditToolMoveUpButtonInDropDownItems {
            get {
                return ResourceManager.GetString("EditToolMoveUpButtonInDropDownItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //table[@id=&apos;ToolsList&apos;]//tbody//tr//td[text()=&apos;{0}&apos;]/..//td//input[contains(@id,&apos;MoveUp&apos;)].
        /// </summary>
        internal static string EditToolMoveUpButtonInListItems {
            get {
                return ResourceManager.GetString("EditToolMoveUpButtonInListItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //tbody//tr[@class=&apos;tableRow&apos;]//td[contains(text(),&apos;{0}&apos;)].
        /// </summary>
        internal static string EditToolsApplicationName {
            get {
                return ResourceManager.GetString("EditToolsApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //tbody/tr[@class=&apos;heading&apos;]//th[contains(text(),&apos;Move&apos;)].
        /// </summary>
        internal static string EditToolsMoveColumnHeader {
            get {
                return ResourceManager.GetString("EditToolsMoveColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //tbody/tr[@class=&apos;heading&apos;]//th[contains(text(),&apos;Name&apos;)].
        /// </summary>
        internal static string EditToolsNameColumnHeader {
            get {
                return ResourceManager.GetString("EditToolsNameColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //tbody//tr[@class=&apos;tableRow&apos;]//td[contains(text(),&apos;{0}&apos;)]/../..//td/input[@value=&apos; Remove &apos;].
        /// </summary>
        internal static string EditToolsRemoveButton {
            get {
                return ResourceManager.GetString("EditToolsRemoveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //tbody/tr//td[contains(@id,&apos;menuNodess&apos;)]/span/a[.=&apos;Edit Tools&apos;].
        /// </summary>
        internal static string EditToolSubMenuOption {
            get {
                return ResourceManager.GetString("EditToolSubMenuOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //tbody//tr//td[contains(text(),&apos;{0}&apos;)]/..//td/input[contains(@id,&apos;ToolsList&apos;) and contains(@value,&apos;Remove&apos;)].
        /// </summary>
        internal static string RemoveCleverToolButton {
            get {
                return ResourceManager.GetString("RemoveCleverToolButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //tbody//tr//td[contains(text(),&apos;{0}&apos;)]/..//td/input[contains(@id,&apos;ToolsDropDownList&apos;) and contains(@value,&apos;Remove&apos;)].
        /// </summary>
        internal static string RemoveCleverToolButtonDropDownList {
            get {
                return ResourceManager.GetString("RemoveCleverToolButtonDropDownList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //table[@id=&apos;ToolsDropDownList&apos;]/tbody//tr[{0}]//td[contains(text(),&apos;{1}&apos;)].
        /// </summary>
        internal static string TableForAppsInDropDownItems {
            get {
                return ResourceManager.GetString("TableForAppsInDropDownItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //table[@id=&apos;ToolsList&apos;]/tbody//tr[{0}]//td[text()=&apos;{1}&apos;].
        /// </summary>
        internal static string TableForAppsInListItems {
            get {
                return ResourceManager.GetString("TableForAppsInListItems", resourceCulture);
            }
        }
    }
}
