//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iDAutomatedUITests.UIElements {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CollectionsLayoutManagerElements {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CollectionsLayoutManagerElements() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("iDAutomatedUITests.UIElements.CollectionsLayoutManagerElements", typeof(CollectionsLayoutManagerElements).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@id=&apos;AddOptionsLayoutDropdownMenu&apos;]//div[@class=&apos;dd_item&apos;]//table/tbody/tr//td/div[@id=&apos;dd_newSubsiteTemplate_Icon&apos;]/../..//td[@class=&apos;dd_itemInner&apos;]/a[@class=&apos;pageActionHeader&apos;].
        /// </summary>
        internal static string AddNewSubsiteTemplate {
            get {
                return ResourceManager.GetString("AddNewSubsiteTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@id=&apos;AddOptionsOff&apos;]/span[@class=&apos;hasLabel&apos;].
        /// </summary>
        internal static string AddOptionOff {
            get {
                return ResourceManager.GetString("AddOptionOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@id=&apos;AddOptionsOn&apos;]/span[@class=&apos;hasLabel&apos;].
        /// </summary>
        internal static string AddOptionOn {
            get {
                return ResourceManager.GetString("AddOptionOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@id=&apos;editSelectorOff&apos;]//span[@class=&apos;hasLabel&apos;].
        /// </summary>
        internal static string EditLayout {
            get {
                return ResourceManager.GetString("EditLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //tbody/tr//td[@class=&apos;dd_itemInner&apos;]/div[@id=&apos;wikiPageControl_wikiHeaderControl_pnDraft&apos;].
        /// </summary>
        internal static string EditLayoutDraft {
            get {
                return ResourceManager.GetString("EditLayoutDraft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@id=&apos;editSelectorOn&apos;]//span[@class=&apos;hasLabel&apos;].
        /// </summary>
        internal static string EditLayoutDropDownList {
            get {
                return ResourceManager.GetString("EditLayoutDropDownList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //tbody/tr//td[@class=&apos;dd_itemInner&apos;]/div[@id=&apos;wikiPageControl_wikiHeaderControl_pnLive&apos;].
        /// </summary>
        internal static string EditLayoutLive {
            get {
                return ResourceManager.GetString("EditLayoutLive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@id=&apos;saveOff&apos;]//span[@class=&apos;hasLabel&apos;].
        /// </summary>
        internal static string EditLayoutSave {
            get {
                return ResourceManager.GetString("EditLayoutSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //tbody/tr//td[@class=&apos;dd_itemInner&apos;]/div[@id=&apos;wikiPageControl_wikiHeaderControl_pnPreview&apos;].
        /// </summary>
        internal static string EditLayoutStaging {
            get {
                return ResourceManager.GetString("EditLayoutStaging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@id=&apos;panelHelp&apos;].
        /// </summary>
        internal static string LayoutHelp {
            get {
                return ResourceManager.GetString("LayoutHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@id=&apos;LayoutActionsDropdownMenu&apos;]//tbody/tr/td/div[@id=&apos;dd_editLayoutProperties_Icon&apos;]/../../td[@class=&apos;dd_itemInner&apos;]/a.
        /// </summary>
        internal static string ManageLayoutActionsEditProperties {
            get {
                return ResourceManager.GetString("ManageLayoutActionsEditProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@id=&apos;layoutActionsOff&apos;]//span[@class=&apos;hasLabel&apos;].
        /// </summary>
        internal static string ManageLayoutActionsOff {
            get {
                return ResourceManager.GetString("ManageLayoutActionsOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@id=&apos;layoutActionsOn&apos;]//span[@class=&apos;hasLabel&apos;].
        /// </summary>
        internal static string ManageLayoutActionsOn {
            get {
                return ResourceManager.GetString("ManageLayoutActionsOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@id=&apos;LayoutActionsDropdownMenu&apos;]//tbody/tr/td/div[@id=&apos;dd_editLayoutRecycle_Icon&apos;]/../../td[@class=&apos;dd_itemInner&apos;]/a.
        /// </summary>
        internal static string ManageLayoutActionsRecycleBin {
            get {
                return ResourceManager.GetString("ManageLayoutActionsRecycleBin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //tbody//tr//td/span/a[.=&apos;{0}&apos;]/../../..//td/input[@type=&apos;radio&apos;].
        /// </summary>
        internal static string ManageLayoutAppliedRadioOptionLocator {
            get {
                return ResourceManager.GetString("ManageLayoutAppliedRadioOptionLocator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //tbody//tr//td/a[.=&apos;{0}&apos;]/../..//td/input[@type=&apos;radio&apos;].
        /// </summary>
        internal static string ManageLayoutDefaultRadioOptionLocator {
            get {
                return ResourceManager.GetString("ManageLayoutDefaultRadioOptionLocator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //tbody//tr//td/span/a[.=&apos;{0}&apos;]/../../..//td/a[.=&apos;Edit&apos;].
        /// </summary>
        internal static string ManageLayoutEditLayoutLocator {
            get {
                return ResourceManager.GetString("ManageLayoutEditLayoutLocator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@id=&apos;jqTabs&apos;]/ul[@class=&apos;ui-tabs-nav ui-helper-reset ui-helper-clearfix ui-widget-header ui-corner-all&apos;]//li/a[@id=&apos;ui-id-1&apos;].
        /// </summary>
        internal static string ManageLayoutLayoutsTab {
            get {
                return ResourceManager.GetString("ManageLayoutLayoutsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //tbody/tr//td[@class=&apos;datagridActionMenu&apos;]//select[contains(@id,&apos;TemplateGrid_idfsdropdownmenu&apos;)].
        /// </summary>
        internal static string ManageLayoutSubsiteTemplatesActionsDropDownList {
            get {
                return ResourceManager.GetString("ManageLayoutSubsiteTemplatesActionsDropDownList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //tbody/tr//td[@class=&apos;datagridActionMenu&apos;]//select[contains(@id,&apos;TemplateGrid_idfsdropdownmenu&apos;)]/option[.=&apos;Delete&apos;].
        /// </summary>
        internal static string ManageLayoutSubsiteTemplatesDeleteOption {
            get {
                return ResourceManager.GetString("ManageLayoutSubsiteTemplatesDeleteOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //input[@class=&apos;systemButtonFixed&apos;].
        /// </summary>
        internal static string ManageLayoutSubsiteTemplatesDeletePopupOkButton {
            get {
                return ResourceManager.GetString("ManageLayoutSubsiteTemplatesDeletePopupOkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@id=&apos;jqTabs&apos;]/ul[@class=&apos;ui-tabs-nav ui-helper-reset ui-helper-clearfix ui-widget-header ui-corner-all&apos;]//li/a[@id=&apos;ui-id-2&apos;].
        /// </summary>
        internal static string ManageLayoutSubsiteTemplatesTab {
            get {
                return ResourceManager.GetString("ManageLayoutSubsiteTemplatesTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //tbody//tr//td//a[.=&apos;{0}&apos;]/../..//td/input[@id=&apos;chkBoxDataGrid&apos;].
        /// </summary>
        internal static string ManageLayoutSubsiteTemplatesTemplateCheckBox {
            get {
                return ResourceManager.GetString("ManageLayoutSubsiteTemplatesTemplateCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //tbody//tr//td/a[.=&apos;{0}&apos;].
        /// </summary>
        internal static string ManageLayoutSubsiteTemplatesTemplateLocator {
            get {
                return ResourceManager.GetString("ManageLayoutSubsiteTemplatesTemplateLocator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@id=&apos;buttonLayoutManage&apos;]//span[@class=&apos;hasLabel&apos;].
        /// </summary>
        internal static string ManagerLayout {
            get {
                return ResourceManager.GetString("ManagerLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@id=&apos;insertTabRow&apos;]/div[@id=&apos;div_5&apos;]/div.
        /// </summary>
        internal static string NewSubisteTemplateComponentsExternal {
            get {
                return ResourceManager.GetString("NewSubisteTemplateComponentsExternal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@id=&apos;templateInsertRowAbove&apos;]/div[@class=&apos;ribbonButton templateRibbonButton&apos;].
        /// </summary>
        internal static string NewSubisteTemplateInsertRowAboveCell {
            get {
                return ResourceManager.GetString("NewSubisteTemplateInsertRowAboveCell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@id=&apos;templateInsertRowBelow&apos;]/div[@class=&apos;ribbonButton templateRibbonButton&apos;].
        /// </summary>
        internal static string NewSubisteTemplateInsertRowBelowCell {
            get {
                return ResourceManager.GetString("NewSubisteTemplateInsertRowBelowCell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@class=&apos;ui-dialog-buttonpane ui-widget-content ui-helper-clearfix&apos;]//input[@value=&apos;&lt; Back&apos;].
        /// </summary>
        internal static string NewSubsiteTemplateBackButton {
            get {
                return ResourceManager.GetString("NewSubsiteTemplateBackButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@class=&apos;ui-dialog-buttonpane ui-widget-content ui-helper-clearfix&apos;]//input[@value=&apos;Cancel&apos;].
        /// </summary>
        internal static string NewSubsiteTemplateCancelButton {
            get {
                return ResourceManager.GetString("NewSubsiteTemplateCancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //td[@arrayrow=&apos;{0}&apos;]//div[@class=&apos;cellBody&apos;]//div[@class=&apos;CellApplicationAreaSelector&apos;]/input.
        /// </summary>
        internal static string NewSubsiteTemplateCellApplicationAreaSelector {
            get {
                return ResourceManager.GetString("NewSubsiteTemplateCellApplicationAreaSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@id=&apos;insertTabRow&apos;]/div[@id=&apos;div_2&apos;]/div.
        /// </summary>
        internal static string NewSubsiteTemplateComponentsApplication {
            get {
                return ResourceManager.GetString("NewSubsiteTemplateComponentsApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@class=&apos;insertComponentsOverflow&apos;]/div[@componentname=&apos;Breadcrumb Bar&apos;].
        /// </summary>
        internal static string NewSubsiteTemplateComponentsFrameworkBreadcrumbBar {
            get {
                return ResourceManager.GetString("NewSubsiteTemplateComponentsFrameworkBreadcrumbBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@class=&apos;insertComponentsOverflow&apos;]/div[@componentname=&apos;iD CMS Page&apos;].
        /// </summary>
        internal static string NewSubsiteTemplateComponentsFrameworkiDCMSPage {
            get {
                return ResourceManager.GetString("NewSubsiteTemplateComponentsFrameworkiDCMSPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@class=&apos;insertComponentsOverflow&apos;]/div[@componentname=&apos;Navigation&apos;].
        /// </summary>
        internal static string NewSubsiteTemplateComponentsFrameworkNavigation {
            get {
                return ResourceManager.GetString("NewSubsiteTemplateComponentsFrameworkNavigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@class=&apos;insertComponentsOverflow&apos;]/div[@componentname=&apos;Search&apos;].
        /// </summary>
        internal static string NewSubsiteTemplateComponentsFrameworkSearch {
            get {
                return ResourceManager.GetString("NewSubsiteTemplateComponentsFrameworkSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@class=&apos;insertComponentsOverflow&apos;]/div[@componentname=&apos;Site Footer&apos;]/div/span.
        /// </summary>
        internal static string NewSubsiteTemplateComponentsFrameworkSiteFooter {
            get {
                return ResourceManager.GetString("NewSubsiteTemplateComponentsFrameworkSiteFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@class=&apos;insertComponentsOverflow&apos;]/div[@componentname=&apos;Site Header&apos;].
        /// </summary>
        internal static string NewSubsiteTemplateComponentsFrameworkSiteHeader {
            get {
                return ResourceManager.GetString("NewSubsiteTemplateComponentsFrameworkSiteHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@class=&apos;insertComponentsOverflow&apos;]/div[@componentname=&apos;Site List&apos;].
        /// </summary>
        internal static string NewSubsiteTemplateComponentsFrameworkSiteList {
            get {
                return ResourceManager.GetString("NewSubsiteTemplateComponentsFrameworkSiteList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@class=&apos;insertComponentsOverflow&apos;]/div[@componentname=&apos;User Manager&apos;].
        /// </summary>
        internal static string NewSubsiteTemplateComponentsFrameworkUserManager {
            get {
                return ResourceManager.GetString("NewSubsiteTemplateComponentsFrameworkUserManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@id=&apos;insertTabRow&apos;]/div[@id=&apos;div_3&apos;]/div.
        /// </summary>
        internal static string NewSubsiteTemplateComponentsMedia {
            get {
                return ResourceManager.GetString("NewSubsiteTemplateComponentsMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@id=&apos;pageControls&apos;]//table[@class=&apos;wikiLayout&apos;]/tbody//tr[{0}]/td/div.
        /// </summary>
        internal static string NewSubsiteTemplateComponentsRowSelector {
            get {
                return ResourceManager.GetString("NewSubsiteTemplateComponentsRowSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@id=&apos;insertTabRow&apos;]/div[@id=&apos;div_-1&apos;]/div.
        /// </summary>
        internal static string NewSubsiteTemplateComponentsShared {
            get {
                return ResourceManager.GetString("NewSubsiteTemplateComponentsShared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@id=&apos;insertTabRow&apos;]/div[@id=&apos;div_1&apos;]/div.
        /// </summary>
        internal static string NewSubsiteTemplateComponentsSiteFramework {
            get {
                return ResourceManager.GetString("NewSubsiteTemplateComponentsSiteFramework", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //tbody/tr//td[@class=&apos;edit&apos;]/div[@id=&apos;dupeMenuComponentTab&apos;]/div.
        /// </summary>
        internal static string NewSubsiteTemplateComponentsTab {
            get {
                return ResourceManager.GetString("NewSubsiteTemplateComponentsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@id=&apos;insertTabRow&apos;]/div[@id=&apos;div_4&apos;]/div.
        /// </summary>
        internal static string NewSubsiteTemplateComponentsText {
            get {
                return ResourceManager.GetString("NewSubsiteTemplateComponentsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //tbody//tr//td/textarea[@id=&apos;AddTemplate_modalWizard_DescriptionTextBox&apos;].
        /// </summary>
        internal static string NewSubsiteTemplateDescriptionTextarea {
            get {
                return ResourceManager.GetString("NewSubsiteTemplateDescriptionTextarea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //table[@class=&apos;modalTable&apos;]/tbody//tr[@id=&apos;templateSaveTr1&apos;]/td/textarea[@id=&apos;templateSaveMessage&apos;].
        /// </summary>
        internal static string NewSubsiteTemplateExitDescriptionTextArea {
            get {
                return ResourceManager.GetString("NewSubsiteTemplateExitDescriptionTextArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@class=&apos;ui-dialog-buttonset&apos;]/button[@class=&apos;ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only&apos;].
        /// </summary>
        internal static string NewSubsiteTemplateExitOkButton {
            get {
                return ResourceManager.GetString("NewSubsiteTemplateExitOkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@class=&apos;ui-dialog-buttonpane ui-widget-content ui-helper-clearfix&apos;]//input[@value=&apos;Finish&apos;].
        /// </summary>
        internal static string NewSubsiteTemplateFinishButton {
            get {
                return ResourceManager.GetString("NewSubsiteTemplateFinishButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@id=&apos;IncludeLeftPane&apos;]/div[@class=&apos;ribbonButton templateRibbonButton&apos;].
        /// </summary>
        internal static string NewSubsiteTemplateInsertCollapsibleLeft {
            get {
                return ResourceManager.GetString("NewSubsiteTemplateInsertCollapsibleLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@id=&apos;IncludeRightPane&apos;]/div[@class=&apos;ribbonButton templateRibbonButton&apos;].
        /// </summary>
        internal static string NewSubsiteTemplateInsertCollapsibleRight {
            get {
                return ResourceManager.GetString("NewSubsiteTemplateInsertCollapsibleRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@id=&apos;templateInsertColumnAfter&apos;]/div[@class=&apos;ribbonButton templateRibbonButton&apos;].
        /// </summary>
        internal static string NewSubsiteTemplateInsertColumnAfterCell {
            get {
                return ResourceManager.GetString("NewSubsiteTemplateInsertColumnAfterCell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@id=&apos;templateInsertColumnBefore&apos;]/div[@class=&apos;ribbonButton templateRibbonButton&apos;].
        /// </summary>
        internal static string NewSubsiteTemplateInsertRowBeforeCell {
            get {
                return ResourceManager.GetString("NewSubsiteTemplateInsertRowBeforeCell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //tbody//td/input[@id=&apos;AddTemplate_modalWizard_NameTextBox&apos;].
        /// </summary>
        internal static string NewSubsiteTemplateNameTextfield {
            get {
                return ResourceManager.GetString("NewSubsiteTemplateNameTextfield", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@class=&apos;ui-dialog-buttonpane ui-widget-content ui-helper-clearfix&apos;]//input[@value=&apos;Next &gt;&apos;].
        /// </summary>
        internal static string NewSubsiteTemplateNextButton {
            get {
                return ResourceManager.GetString("NewSubsiteTemplateNextButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //tbody/tr//td[@class=&apos;edit&apos;]/div[@id=&apos;dupeMenuPropertiesTab&apos;]/div.
        /// </summary>
        internal static string NewSubsiteTemplatePropertiesTab {
            get {
                return ResourceManager.GetString("NewSubsiteTemplatePropertiesTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //tbody/tr//td[@arrayrow=&apos;{0}&apos;].
        /// </summary>
        internal static string NewSubsiteTemplateRowSelector {
            get {
                return ResourceManager.GetString("NewSubsiteTemplateRowSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //tbody/tr//td[@class=&apos;actionButton&apos;]/div[@class=&apos;saveExit&apos;]/a.
        /// </summary>
        internal static string NewSubsiteTemplateSaveButton {
            get {
                return ResourceManager.GetString("NewSubsiteTemplateSaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@id=&apos;templateButtonRow&apos;]//div[@id=&apos;templateButtonDelete&apos;]/div.
        /// </summary>
        internal static string NewSubsiteTemplateStructureDelete {
            get {
                return ResourceManager.GetString("NewSubsiteTemplateStructureDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@id=&apos;templateButtonRow&apos;]//div[@id=&apos;cellPropertiesButton&apos;]/div.
        /// </summary>
        internal static string NewSubsiteTemplateStructureEditCurrentCell {
            get {
                return ResourceManager.GetString("NewSubsiteTemplateStructureEditCurrentCell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@id=&apos;templateButtonRow&apos;]//div[@id=&apos;templateButtonImport&apos;]/div.
        /// </summary>
        internal static string NewSubsiteTemplateStructureImport {
            get {
                return ResourceManager.GetString("NewSubsiteTemplateStructureImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@id=&apos;templateButtonRow&apos;]//div[@id=&apos;templateButtonInsert&apos;]/div.
        /// </summary>
        internal static string NewSubsiteTemplateStructureInsert {
            get {
                return ResourceManager.GetString("NewSubsiteTemplateStructureInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@id=&apos;templateButtonRow&apos;]//div[@id=&apos;templateButtonMerge&apos;]/div.
        /// </summary>
        internal static string NewSubsiteTemplateStructureMerge {
            get {
                return ResourceManager.GetString("NewSubsiteTemplateStructureMerge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //tbody/tr//td[@class=&apos;edit&apos;]/div[@id=&apos;panelInsert&apos;]/div.
        /// </summary>
        internal static string NewSubsiteTemplateStructureTab {
            get {
                return ResourceManager.GetString("NewSubsiteTemplateStructureTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@id=&apos;templateButtonRow&apos;]//div[@id=&apos;templateButtonDivide&apos;]/div.
        /// </summary>
        internal static string NewSubsiteTemplateStructureUnmerge {
            get {
                return ResourceManager.GetString("NewSubsiteTemplateStructureUnmerge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //tbody/tr//td[@class=&apos;edit&apos;]/div[@id=&apos;dupeMenuVersionControlTab&apos;]/div.
        /// </summary>
        internal static string NewSubsiteTemplateVersionControlTab {
            get {
                return ResourceManager.GetString("NewSubsiteTemplateVersionControlTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@id=&apos;AddOptionsLayoutDropdownMenu&apos;]//div[@class=&apos;dd_item&apos;]//table/tbody/tr//td/div[@id=&apos;dd_newLayout_Icon&apos;]/../..//td[@class=&apos;dd_itemInner&apos;]/a[@class=&apos;pageActionHeader&apos;].
        /// </summary>
        internal static string stewart {
            get {
                return ResourceManager.GetString("stewart", resourceCulture);
            }
        }
    }
}
