//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iDAutomatedUITests.UIElements {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CollectionsEditLayoutElements {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CollectionsEditLayoutElements() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("iDAutomatedUITests.UIElements.CollectionsEditLayoutElements", typeof(CollectionsEditLayoutElements).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@id=&apos;wikiPageControl_wikiHeaderControl_genericActionMenu_genericActionMenu_layoutActionsOff&apos;]/div[@id=&apos;layoutActionsOff&apos;]/span[@class=&apos;hasLabel&apos;].
        /// </summary>
        internal static string EditLayoutActionOption {
            get {
                return ResourceManager.GetString("EditLayoutActionOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //table/tbody/tr/td[@class=&apos;dd_iconHolder&apos;]/div[@id=&apos;dd_deleteLayout_Icon&apos;]/../..//td[@class=&apos;dd_itemInner&apos;]/a.
        /// </summary>
        internal static string EditLayoutActionsDeleteLayout {
            get {
                return ResourceManager.GetString("EditLayoutActionsDeleteLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@id=&apos;wikiPageControl_wikiHeaderControl_genericActionMenu_genericActionMenu_layoutActionsOn&apos;]/div[@id=&apos;layoutActionsOn&apos;]/span[@class=&apos;hasLabel&apos;].
        /// </summary>
        internal static string EditLayoutActionsDropDownList {
            get {
                return ResourceManager.GetString("EditLayoutActionsDropDownList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //table/tbody/tr/td[@class=&apos;dd_iconHolder&apos;]/div[@id=&apos;dd_editLayoutProperties_Icon&apos;]/../..//td[@class=&apos;dd_itemInner&apos;]/a.
        /// </summary>
        internal static string EditLayoutActionsEditProperties {
            get {
                return ResourceManager.GetString("EditLayoutActionsEditProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //table/tbody/tr/td[@class=&apos;dd_iconHolder&apos;]/div[@id=&apos;dd_moveLayout_Icon&apos;]/../..//td[@class=&apos;dd_itemInner&apos;]/a.
        /// </summary>
        internal static string EditLayoutActionsMoveLayout {
            get {
                return ResourceManager.GetString("EditLayoutActionsMoveLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //table/tbody/tr/td[@class=&apos;dd_iconHolder&apos;]/div[@id=&apos;dd_revertLayout_Icon&apos;]/../..//td[@class=&apos;dd_itemInner&apos;]/a.
        /// </summary>
        internal static string EditLayoutActionsRevertLayout {
            get {
                return ResourceManager.GetString("EditLayoutActionsRevertLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //input[@id=&apos;ApplyLayout&apos;].
        /// </summary>
        internal static string EditLayoutApplyLayoutCheckBox {
            get {
                return ResourceManager.GetString("EditLayoutApplyLayoutCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@class=&apos;ui-dialog-buttonset&apos;]//button[2]/span.
        /// </summary>
        internal static string EditLayoutCancelButtonSavePopup {
            get {
                return ResourceManager.GetString("EditLayoutCancelButtonSavePopup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@id=&apos;wikiPageControl_wikiHeaderControl_genericActionMenu_genericActionMenu_panelInsert&apos;]/div[@id=&apos;panelInsert&apos;]/div.
        /// </summary>
        internal static string EditLayoutComponentsTab {
            get {
                return ResourceManager.GetString("EditLayoutComponentsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@id=&apos;editDropdownMenu&apos;]//div[@class=&apos;dd_item&apos;]/table/tbody/tr//td[@class=&apos;dd_itemInner&apos;]/div[@id=&apos;wikiPageControl_wikiHeaderControl_pnDraft&apos;]/a.
        /// </summary>
        internal static string EditLayoutEditDraft {
            get {
                return ResourceManager.GetString("EditLayoutEditDraft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@id=&apos;wikiPageControl_wikiHeaderControl_genericActionMenu_genericActionMenu_editSelectorOn&apos;]/div[@id=&apos;editSelectorOn&apos;]//span[@class=&apos;hasLabel&apos;].
        /// </summary>
        internal static string EditLayoutEditDropDownList {
            get {
                return ResourceManager.GetString("EditLayoutEditDropDownList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //table/tbody/tr//td[@class=&apos;dd_itemInner&apos;]/div[@id=&apos;wikiPageControl_wikiHeaderControl_pnLive&apos;]/a.
        /// </summary>
        internal static string EditLayoutEditLive {
            get {
                return ResourceManager.GetString("EditLayoutEditLive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@id=&apos;wikiPageControl_wikiHeaderControl_genericActionMenu_genericActionMenu_editSelectorOff&apos;]/div[@id=&apos;editSelectorOff&apos;]//span[@class=&apos;hasLabel&apos;].
        /// </summary>
        internal static string EditLayoutEditOption {
            get {
                return ResourceManager.GetString("EditLayoutEditOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //table/tbody/tr//td[@class=&apos;dd_itemInner&apos;]/div[@id=&apos;wikiPageControl_wikiHeaderControl_pnPreview&apos;]/a.
        /// </summary>
        internal static string EditLayoutEditStaging {
            get {
                return ResourceManager.GetString("EditLayoutEditStaging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@id=&apos;wikiPageControl_wikiHeaderControl_genericActionMenu_genericActionMenu_manageLayoutOption&apos;]/div[@id=&apos;manageLayoutOption&apos;]//span[@class=&apos;hasLabel&apos;].
        /// </summary>
        internal static string EditLayoutManageLayout {
            get {
                return ResourceManager.GetString("EditLayoutManageLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@id=&apos;saveDropDownMenu&apos;]//div[@class=&apos;dd_item&apos;]/table/tbody/tr/td/div[@id=&apos;dd_publishLive_Icon&apos;]/../..//td[@class=&apos;dd_itemInner&apos;]/a.
        /// </summary>
        internal static string EditLayoutPublishLiveExit {
            get {
                return ResourceManager.GetString("EditLayoutPublishLiveExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@id=&apos;saveDropDownMenu&apos;]//div[@class=&apos;dd_item&apos;]/table/tbody/tr/td/div[@id=&apos;dd_publishPreview_Icon&apos;]/../..//td[@class=&apos;dd_itemInner&apos;]/a.
        /// </summary>
        internal static string EditLayoutPublishStagingExit {
            get {
                return ResourceManager.GetString("EditLayoutPublishStagingExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@class=&apos;ui-dialog-buttonset&apos;]//button[1]/span.
        /// </summary>
        internal static string EditLayoutSaveButtonSavePopup {
            get {
                return ResourceManager.GetString("EditLayoutSaveButtonSavePopup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //textarea[@id=&apos;svMessage&apos;].
        /// </summary>
        internal static string EditLayoutSaveDescriptionTextArea {
            get {
                return ResourceManager.GetString("EditLayoutSaveDescriptionTextArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@id=&apos;saveDropDownMenu&apos;]//div[@class=&apos;dd_item&apos;]/table/tbody/tr/td/div[@id=&apos;dd_saveDraftContinue_Icon&apos;]/../..//td[@class=&apos;dd_itemInner&apos;]/a.
        /// </summary>
        internal static string EditLayoutSaveDraftContinueEditing {
            get {
                return ResourceManager.GetString("EditLayoutSaveDraftContinueEditing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@id=&apos;saveDropDownMenu&apos;]//div[@class=&apos;dd_item&apos;]/table/tbody/tr/td/div[@id=&apos;dd_saveDraftExit_Icon&apos;]/../..//td[@class=&apos;dd_itemInner&apos;]/a.
        /// </summary>
        internal static string EditLayoutSaveDraftExit {
            get {
                return ResourceManager.GetString("EditLayoutSaveDraftExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@id=&apos;wikiPageControl_wikiHeaderControl_genericActionMenu_genericActionMenu_saveOn&apos;]/div[@id=&apos;saveOn&apos;]//span[@class=&apos;hasLabel&apos;].
        /// </summary>
        internal static string EditLayoutSaveDropDownList {
            get {
                return ResourceManager.GetString("EditLayoutSaveDropDownList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //table[@id=&apos;dupeMenu&apos;]//tbody//tr//td[@class=&apos;actionButton&apos;]/div[@class=&apos;saveExit&apos;].
        /// </summary>
        internal static string EditLayoutSaveEditing {
            get {
                return ResourceManager.GetString("EditLayoutSaveEditing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@id=&apos;wikiPageControl_wikiHeaderControl_genericActionMenu_genericActionMenu_saveOff&apos;]/div[@id=&apos;saveOff&apos;]//span[@class=&apos;hasLabel&apos;].
        /// </summary>
        internal static string EditLayoutSaveOption {
            get {
                return ResourceManager.GetString("EditLayoutSaveOption", resourceCulture);
            }
        }
    }
}
