//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iDAutomatedUITests.UIElements {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class QuickPollAddPollAdminElements {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal QuickPollAddPollAdminElements() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("iDAutomatedUITests.UIElements.QuickPollAddPollAdminElements", typeof(QuickPollAddPollAdminElements).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //tbody/tr//td[contains(@id,&apos;menuNodess&apos;)]/span/a[.=&apos;Add Poll&apos;].
        /// </summary>
        internal static string AddPollSubMenuOption {
            get {
                return ResourceManager.GetString("AddPollSubMenuOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //input[@id=&apos;Active&apos;].
        /// </summary>
        internal static string EditPollActiveCheckBox {
            get {
                return ResourceManager.GetString("EditPollActiveCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //input[@id=&apos;AddAnswer&apos;].
        /// </summary>
        internal static string EditPollAddNewAnswerButton {
            get {
                return ResourceManager.GetString("EditPollAddNewAnswerButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //input[@id=&apos;MultiVote&apos;].
        /// </summary>
        internal static string EditPollAllowMultipleVotesCheckbox {
            get {
                return ResourceManager.GetString("EditPollAllowMultipleVotesCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@id=&apos;EditPollPage&apos;]/ul/li/a[.=&apos;Answers&apos;].
        /// </summary>
        internal static string EditPollAnswersTab {
            get {
                return ResourceManager.GetString("EditPollAnswersTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //table[@id=&apos;QuickPollAnswers&apos;]/tbody//tr[{0}]//td[01]/input[contains(@id,&apos;QuickPollAnswers&apos;)].
        /// </summary>
        internal static string EditPollAnswerTextBox {
            get {
                return ResourceManager.GetString("EditPollAnswerTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //input[@id=&apos;EditPoll_Apply&apos;].
        /// </summary>
        internal static string EditPollApplyButton {
            get {
                return ResourceManager.GetString("EditPollApplyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //input[@id=&apos;EditPoll_Cancel&apos;].
        /// </summary>
        internal static string EditPollCancelButton {
            get {
                return ResourceManager.GetString("EditPollCancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //tbody//tr//span[text()=&apos;{0}&apos;]/../../../td[7].
        /// </summary>
        internal static string EditPollEditLink {
            get {
                return ResourceManager.GetString("EditPollEditLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //input[@id=&apos;EditPoll_Ok&apos;].
        /// </summary>
        internal static string EditPollOKButton {
            get {
                return ResourceManager.GetString("EditPollOKButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@id=&apos;EditPollPage&apos;]/ul/li/a[.=&apos;Question&apos;].
        /// </summary>
        internal static string EditPollQuestionsTab {
            get {
                return ResourceManager.GetString("EditPollQuestionsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //input[@id=&apos;QuickPollQuestion&apos;].
        /// </summary>
        internal static string EditPollQuestionTextBox {
            get {
                return ResourceManager.GetString("EditPollQuestionTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //tbody/tr//td[contains(@id,&apos;menuNodess&apos;)]/span/a[.=&apos;Edit Poll&apos;].
        /// </summary>
        internal static string EditPollSubMenuOption {
            get {
                return ResourceManager.GetString("EditPollSubMenuOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@class=&apos;clearFloat&apos;]//input[@id=&apos;AddAnswer&apos;].
        /// </summary>
        internal static string StepAnswersAddAnswerButton {
            get {
                return ResourceManager.GetString("StepAnswersAddAnswerButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //table[@id=&apos;AddAnswers&apos;]/tbody//tr[02]//td[02]//input[contains(@id,&apos;RemoveAnswer&apos;)].
        /// </summary>
        internal static string StepAnswersAnswerRemoveButton1 {
            get {
                return ResourceManager.GetString("StepAnswersAnswerRemoveButton1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //table[@id=&apos;AddAnswers&apos;]/tbody//tr[03]//td[02]//input[contains(@id,&apos;RemoveAnswer&apos;)].
        /// </summary>
        internal static string StepAnswersAnswerRemoveButton2 {
            get {
                return ResourceManager.GetString("StepAnswersAnswerRemoveButton2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //table[@id=&apos;AddAnswers&apos;]/tbody//tr[{0}]//td[01]/div/input[contains(@id,&apos;AddAnswers&apos;)].
        /// </summary>
        internal static string StepAnswersAnswerTextBox {
            get {
                return ResourceManager.GetString("StepAnswersAnswerTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //table[@id=&apos;AddAnswers&apos;]/tbody//tr[02]//td[01]//input[contains(@id,&apos;QuickPollAnswer&apos;)].
        /// </summary>
        internal static string StepAnswersAnswerTextBox1 {
            get {
                return ResourceManager.GetString("StepAnswersAnswerTextBox1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //table[@id=&apos;AddAnswers&apos;]/tbody//tr[03]//td[01]//input[contains(@id,&apos;QuickPollAnswer&apos;)].
        /// </summary>
        internal static string StepAnswersAnswerTextBox2 {
            get {
                return ResourceManager.GetString("StepAnswersAnswerTextBox2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //table[@id=&apos;AddAnswers&apos;]/tbody//tr[04]//td[01]//input[contains(@id,&apos;QuickPollAnswer&apos;)].
        /// </summary>
        internal static string StepAnswersAnswerTextBox3 {
            get {
                return ResourceManager.GetString("StepAnswersAnswerTextBox3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //input[@id=&apos;ReadMoreLink&apos;].
        /// </summary>
        internal static string StepAnswersReadMoreLinkTextBox {
            get {
                return ResourceManager.GetString("StepAnswersReadMoreLinkTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //tbody//tr&apos;{0}&apos;//td/div/input[contains(@id,&apos;RemoveAnswer&apos;)].
        /// </summary>
        internal static string StepAnswersRemoveButton {
            get {
                return ResourceManager.GetString("StepAnswersRemoveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@class=&apos;wz_buttons&apos;]//input[@id=&apos;AddPoll_Back&apos;].
        /// </summary>
        internal static string StepBackButton {
            get {
                return ResourceManager.GetString("StepBackButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@class=&apos;wz_buttons&apos;]//input[@id=&apos;AddPoll_Cancel&apos;].
        /// </summary>
        internal static string StepCancelButton {
            get {
                return ResourceManager.GetString("StepCancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //span[@id=&apos;ActiveFinish&apos;]/img[contains(@src,&apos;False.gif&apos;)].
        /// </summary>
        internal static string StepFinishActiveFalseValue {
            get {
                return ResourceManager.GetString("StepFinishActiveFalseValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //span[@id=&apos;ActiveFinish&apos;]/img[contains(@src,&apos;True.gif&apos;)].
        /// </summary>
        internal static string StepFinishActiveTrueValue {
            get {
                return ResourceManager.GetString("StepFinishActiveTrueValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //span[@id=&apos;MultiVoteValue&apos;]/img[contains(@src,&apos;False.gif&apos;)].
        /// </summary>
        internal static string StepFinishAllowMultipleVotesPerUserFalseValue {
            get {
                return ResourceManager.GetString("StepFinishAllowMultipleVotesPerUserFalseValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //span[@id=&apos;MultiVoteValue&apos;]/img[contains(@src,&apos;True.gif&apos;)].
        /// </summary>
        internal static string StepFinishAllowMultipleVotesPerUserTrueValue {
            get {
                return ResourceManager.GetString("StepFinishAllowMultipleVotesPerUserTrueValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //table[@id=&apos;FinalisedAnswers&apos;]/tbody//tr[02]//span[contains(@id,&apos;FinalisedAnswers&apos;)].
        /// </summary>
        internal static string StepFinishAnswerValue1 {
            get {
                return ResourceManager.GetString("StepFinishAnswerValue1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //table[@id=&apos;FinalisedAnswers&apos;]/tbody//tr[03]//span[contains(@id,&apos;FinalisedAnswers&apos;)].
        /// </summary>
        internal static string StepFinishAnswerValue2 {
            get {
                return ResourceManager.GetString("StepFinishAnswerValue2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@class=&apos;wz_buttons&apos;]//input[@id=&apos;AddPoll_Finish&apos;].
        /// </summary>
        internal static string StepFinishButton {
            get {
                return ResourceManager.GetString("StepFinishButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //span[@id=&apos;QuestionBoxFinish&apos;].
        /// </summary>
        internal static string StepFinishQuestionValue {
            get {
                return ResourceManager.GetString("StepFinishQuestionValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //span[@id=&apos;ReadMoreLinkFinish&apos;].
        /// </summary>
        internal static string StepFinishReadMoreLinkValue {
            get {
                return ResourceManager.GetString("StepFinishReadMoreLinkValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //span[@id=&apos;PollTypeFinish&apos;].
        /// </summary>
        internal static string StepFinishTypeValue {
            get {
                return ResourceManager.GetString("StepFinishTypeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@class=&apos;wz_buttons&apos;]//input[@id=&apos;AddPoll_Next&apos;].
        /// </summary>
        internal static string StepNextButton {
            get {
                return ResourceManager.GetString("StepNextButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //input[@id=&apos;Active&apos;].
        /// </summary>
        internal static string StepQuestionActiveCheckBox {
            get {
                return ResourceManager.GetString("StepQuestionActiveCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //input[@id=&apos;MultiVote&apos;].
        /// </summary>
        internal static string StepQuestionAllowMultipleVotesPerUserCheckBox {
            get {
                return ResourceManager.GetString("StepQuestionAllowMultipleVotesPerUserCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //input[@id=&apos;AddPollQuestion&apos;].
        /// </summary>
        internal static string StepQuestionQuestionTextBox {
            get {
                return ResourceManager.GetString("StepQuestionQuestionTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@id=&apos;PollType&apos;]//input[@id=&apos;Poll&apos;].
        /// </summary>
        internal static string StepTypePollRadioButton {
            get {
                return ResourceManager.GetString("StepTypePollRadioButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //table[@id=&apos;Questions&apos;]/tbody//tr//span[text()=&apos;{0}&apos;].
        /// </summary>
        internal static string VerifyQuestion {
            get {
                return ResourceManager.GetString("VerifyQuestion", resourceCulture);
            }
        }
    }
}
