//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iDAutomatedUITests.UIElements.NavEditor {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class NavEditor {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NavEditor() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("iDAutomatedUITests.UIElements.NavEditor.NavEditor", typeof(NavEditor).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@class=&apos;button button-addmenu&apos;].
        /// </summary>
        internal static string AddNavMenu {
            get {
                return ResourceManager.GetString("AddNavMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&apos;CustomEditButtons_Apply&apos;].
        /// </summary>
        internal static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[text()=&apos;New Item&apos;].
        /// </summary>
        internal static string FeNav {
            get {
                return ResourceManager.GetString("FeNav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //span[text()= &apos;Home&apos;].
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&quot;tree1&quot;]/div/div/table[2]/tbody/tr/td[2]/div[1]/table[2]/tbody/tr/td[2]/div[1]/table[1]/tbody/tr/td[1]/img.
        /// </summary>
        internal static string HomeExpand {
            get {
                return ResourceManager.GetString("HomeExpand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //a[text()=&apos;Edit Nav Bar&apos;].
        /// </summary>
        internal static string NavEdit {
            get {
                return ResourceManager.GetString("NavEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&apos;ui-id-2&apos;].
        /// </summary>
        internal static string NavItems {
            get {
                return ResourceManager.GetString("NavItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //a[text()=&apos;Nav Editor&apos;].
        /// </summary>
        internal static string NavLink {
            get {
                return ResourceManager.GetString("NavLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&apos;VerticalDataGrid_ctl03_VerticalEditLink&apos;].
        /// </summary>
        internal static string VerticalEdit {
            get {
                return ResourceManager.GetString("VerticalEdit", resourceCulture);
            }
        }
    }
}
