//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iDAutomatedUITests.UIElements.CMS.Templates {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Templates {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Templates() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("iDAutomatedUITests.UIElements.CMS.Templates.Templates", typeof(Templates).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //a[contains(text(),&apos;Announcement Template&apos;)].
        /// </summary>
        internal static string Template1 {
            get {
                return ResourceManager.GetString("Template1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //a[contains(text(),&apos;Document Index Template&apos;)].
        /// </summary>
        internal static string Template2 {
            get {
                return ResourceManager.GetString("Template2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //a[contains(text(),&apos;Extensive Text Template&apos;)].
        /// </summary>
        internal static string Template3 {
            get {
                return ResourceManager.GetString("Template3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //a[contains(text(),&apos;Image Grid Template&apos;)].
        /// </summary>
        internal static string Template4 {
            get {
                return ResourceManager.GetString("Template4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //a[contains(text(),&apos;Text Video Images Template&apos;)].
        /// </summary>
        internal static string Template5 {
            get {
                return ResourceManager.GetString("Template5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@id=&apos;pt-tab-title_masterPageTabs_tabItem-1&apos;].
        /// </summary>
        internal static string TemplatesTab {
            get {
                return ResourceManager.GetString("TemplatesTab", resourceCulture);
            }
        }
    }
}
