//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iDAutomatedUITests.UIElements.LayoutManager.SubsiteTemplates {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SubsiteTemplates {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SubsiteTemplates() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("iDAutomatedUITests.UIElements.LayoutManager.SubsiteTemplates.SubsiteTemplates", typeof(SubsiteTemplates).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //a[contains(text(),&apos;Complex Grid - LComplex Grid - L&amp;R Columns&apos;)].
        /// </summary>
        internal static string SubsiteTemplate1 {
            get {
                return ResourceManager.GetString("SubsiteTemplate1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //a[contains(text(),&apos;Grid Main Area - Left Column&apos;)].
        /// </summary>
        internal static string SubsiteTemplate2 {
            get {
                return ResourceManager.GetString("SubsiteTemplate2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //a[contains(text(),&apos;Grid Main Area - LGrid Main Area - L&amp;R Columns&apos;)].
        /// </summary>
        internal static string SubsiteTemplate3 {
            get {
                return ResourceManager.GetString("SubsiteTemplate3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //a[contains(text(),&apos;Grid Main Area - Right Column&apos;)].
        /// </summary>
        internal static string SubsiteTemplate4 {
            get {
                return ResourceManager.GetString("SubsiteTemplate4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //a[contains(text(),&apos;Three Panel Main Area&apos;)].
        /// </summary>
        internal static string SubsiteTemplate5 {
            get {
                return ResourceManager.GetString("SubsiteTemplate5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@id=&apos;pt-tab-title_masterPageTabs_tabItem-1&apos;].
        /// </summary>
        internal static string SubsiteTemplatesTab {
            get {
                return ResourceManager.GetString("SubsiteTemplatesTab", resourceCulture);
            }
        }
    }
}
